# Generated by Django 3.2.3 on 2021-05-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
