# Generated by Django 3.2.3 on 2021-05-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_polls_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='link',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
