# Generated by Django 3.2.3 on 2021-05-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_polls_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polls',
            old_name='link',
            new_name='address',
        ),
    ]
