# Generated by Django 3.2.3 on 2021-06-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_link_polls_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polls',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='polls',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='is_active',
            field=models.BooleanField(default=True, help_text='mark poll as open'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='start_date',
            field=models.DateField(),
        ),
    ]
