# Generated by Django 3.2.3 on 2021-06-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_polls_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='start_time',
        ),
    ]
