# Generated by Django 3.2.3 on 2021-05-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='participant',
            name='stack',
            field=models.CharField(choices=[('FrontEnd', 'FrontEnd'), ('BackEnd', 'BackEnd'), ('FullStack', 'FullStack')], default=('FrontEnd', 'FrontEnd'), max_length=30),
        ),
    ]
