# Generated by Django 3.2.3 on 2021-05-31 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        ('participants', '0002_auto_20210531_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='polls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.polls'),
        ),
    ]
