# Generated by Django 3.2.3 on 2021-05-31 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        ('participants', '0003_participant_polls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='polls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polls'),
        ),
    ]
