# Generated by Django 3.2.3 on 2021-05-31 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        ('participants', '0005_alter_participant_polls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='polls',
        ),
        migrations.CreateModel(
            name='ParticipantPolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_link', models.CharField(default='', max_length=100, unique=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
                ('polls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polls')),
            ],
        ),
    ]
