# Generated by Django 3.2.3 on 2021-05-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_alter_participantpolls_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpolls',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
