# Generated by Django 3.2.3 on 2021-05-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_auto_20210531_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantpolls',
            name='project_link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
