# Generated by Django 3.2.3 on 2021-06-06 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0002_rename_judgespolls_judgespoll'),
        ('participants', '0010_alter_participantpolls_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpolls',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judges.judgespoll'),
        ),
    ]
