# Generated by Django 3.2.3 on 2021-06-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0013_alter_participantpolls_judge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantpolls',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='participantpolls',
            name='project_link',
        ),
    ]
