# Generated by Django 3.2.3 on 2021-06-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0014_auto_20210610_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpolls',
            name='project_link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
