# Generated by Django 3.2.3 on 2021-06-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0015_participantpolls_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpolls',
            name='number_of_votes',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='vote couuts'),
        ),
        migrations.AddField(
            model_name='participantpolls',
            name='total_rating',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='total nuber of rating'),
        ),
    ]
