# Generated by Django 3.2.3 on 2021-06-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0016_auto_20210614_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantpolls',
            name='number_of_votes',
        ),
    ]
