# Generated by Django 3.2.3 on 2021-06-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0017_remove_participantpolls_number_of_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantpolls',
            options={'ordering': ['-total_rating']},
        ),
    ]
