# Generated by Django 3.2.4 on 2021-07-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0018_alter_participantpolls_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='image',
            field=models.ImageField(default='participant)image.png', upload_to='participant_profile_images'),
        ),
    ]
