# Generated by Django 3.2.4 on 2021-07-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0019_participant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=models.ImageField(default='participant_image.png', upload_to='participant_profile_images'),
        ),
    ]
