# Generated by Django 3.2.3 on 2021-06-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_link_polls_address'),
        ('judges', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JudgesPolls',
            new_name='JudgesPoll',
        ),
    ]
