# Generated by Django 3.2.3 on 2021-06-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0014_auto_20210610_1627'),
        ('judges', '0002_rename_judgespolls_judgespoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgespoll',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='judgespoll',
            name='voted_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.participantpolls'),
        ),
    ]
