# Generated by Django 3.2.3 on 2021-06-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0018_alter_participantpolls_options'),
        ('judges', '0007_judgespoll_is_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgespoll',
            name='voted_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.participantpolls'),
        ),
    ]
