# Generated by Django 3.2.4 on 2021-07-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0019_participant_image'),
        ('judges', '0008_alter_judgespoll_voted_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgespoll',
            name='voted_participant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.participantpolls'),
        ),
    ]
